load("@rules_javascript//typescript/internal:toolchain.bzl", "typescript_toolchain_alias")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

typescript_toolchain_alias(
    name = "toolchain",
    visibility = ["//visibility:public"],
)
