load("@rules_javascript//tools/eslint/internal:toolchain.bzl", "eslint_toolchain_alias")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

eslint_toolchain_alias(
    name = "toolchain",
    visibility = ["//visibility:public"],
)
