load("@rules_javascript//tools/yarn/internal:toolchain.bzl", "yarn_toolchain_alias")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

yarn_toolchain_alias(
    name = "toolchain",
    visibility = ["//visibility:public"],
)
