filegroup(
    name = "all_srcs",
    srcs = glob(["**/*"]),
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "helper_js",
    srcs = [":helper.js"],
    visibility = ["//:__subpackages__"],
)
