filegroup(
    name = "all_srcs",
    srcs = glob(["**/*"]) + [
        "//javascript/constraints/engine:all_srcs",
        "//javascript/constraints/runtime:all_srcs",
    ],
    visibility = ["//:__subpackages__"],
)
