load("@rules_javascript//tools/webpack/internal:toolchain.bzl", "webpack_toolchain_alias")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

webpack_toolchain_alias(
    name = "toolchain",
    visibility = ["//visibility:public"],
)
