load("@rules_javascript//tools/babel/internal:toolchain.bzl", "babel_toolchain_alias")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

babel_toolchain_alias(
    name = "toolchain",
    visibility = ["//visibility:public"],
)
