load("@rules_javascript//javascript/node/internal:toolchain.bzl", "node_toolchain_alias")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

node_toolchain_alias(
    name = "toolchain",
    visibility = ["//visibility:public"],
)
